# The following will install necessary R packages for this course
install.packages(c(
  'bitops',
  'caTools',
  'caret',
  'data.table',
  'devtools',
  'gbm',
  'ggplot2',
  'h2o',
  'htmltools',
  'kknn',
  'knitr',
  'knitr',
  'markdown',
  'MASS',
  'parRF',
  'randomForest',
  'rpart',
  'RCurl',
  'rmarkdown',
  'tree',
  'yaml'),
  dependencies = TRUE,
  repos="http://cran.rstudio.com")
